"""Fix foreign key issue

Revision ID: 41913ab291f1
Revises: fa7d0523e1bf
Create Date: 2025-03-20 16:08:38.619104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41913ab291f1'
down_revision = 'fa7d0523e1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_commander_decks')
    with op.batch_alter_table('commander_decks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_associated_commander', type_='foreignkey')
        batch_op.drop_column('associated_commander_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commander_decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('associated_commander_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_associated_commander', 'commanders', ['associated_commander_id'], ['id'])

    op.create_table('new_commander_decks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deck_id', sa.INTEGER(), nullable=False),
    sa.Column('commander_id', sa.INTEGER(), nullable=False),
    sa.Column('associated_commander_id', sa.INTEGER(), nullable=True),
    sa.Column('relationship_type', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['commander_id'], ['commanders.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
